apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dev
  labels:
    app: test
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
      env: dev
  template:
    metadata:
      labels:
        app: test
        env: dev
    spec:
      containers:
      - name: test
        image: docker.io/sivanext/finalsemproject:latest
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
