apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-getting-started-dev
  labels:
    app: python-getting-started
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-getting-started
      env: dev
  template:
    metadata:
      labels:
        app: python-getting-started
        env: dev
    spec:
      containers:
      - name: python-getting-started
        image: docker.io/sivanext/finalsemproject:latest
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
