apiVersion: v1
kind: Service
metadata:
  name: python-getting-started-dev-svc
spec:
  selector:
    app: python-getting-started
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
